GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW9uZyIsImlhdCI6MTc0MjgyNTc4NSwiZXhwIjoxNzQyODI1ODAwfQ.fooEVYgLi3yCHfx3JFN_Wcamt8l2UM-HBBlgErScNHw


###
POST http://localhost:8000/login1
Content-Type: application/json

{
    "username" : "ahihihi1680@gmail.com",
    "password" : "123456"
}

###
POST http://localhost:8000/token 
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW9uZyIsImlhdCI6MTc0MjYzOTAxMCwiZXhwIjoxNzQyNjQyNjEwfQ.DFh_lngT-ifg9GtT_-p1UOm288KwVqqbRYhqZW1FUW4"
}

###
POST http://localhost:8080/loginAcc
Content-Type: application/json

{
    "username" : "luong"
}

###
POST http://localhost:8000/test1
Content-Type: application/json

{
    "username" : "ahihihi1680@gmail.com",
    "password" : "12345"
}