GET http://localhost:8080/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDMyMTg5ODUsImV4cCI6MTc0MzIxOTAwMH0.PNVQ_pQLoW2ArxulOqptKWj9wFZZH3sVhHmUHTsp8kY

###
POST http://localhost:8000/login1
Content-Type: application/json

{
    "username" : "ahihihi1680@gmail.com",
    "password" : "123456"
}

###
POST http://localhost:8000/token 
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJsdW9uZyIsImlhdCI6MTc0MjYzOTAxMCwiZXhwIjoxNzQyNjQyNjEwfQ.DFh_lngT-ifg9GtT_-p1UOm288KwVqqbRYhqZW1FUW4"
}

###
POST http://localhost:8080/loginAcc
Content-Type: application/json

{
    "username" : "ahihihi1680@gmail.com",
    "password" : "123456"
}

###
POST http://localhost:8000/test1
Content-Type: application/json

{
    "username" : "ahihihi1680@gmail.com",
    "password" : "12345"
}

###
GET http://localhost:8080/homePage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDMyNDI0MDV9.RgoPiGfqYAy5yZe1CX842w6kAYAbQOm0oYtF6WkBDZw